[profile.default]
src = "contracts"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
